services:
  app:
    build: .
    container_name: presensi-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=presensi
      - DB_USERNAME=presensi_user
      - DB_PASSWORD=secure_password_123
    depends_on:
      - mysql
    networks:
      - presensi-network

  mysql:
    image: mysql:8.0
    container_name: presensi-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: presensi
      MYSQL_USER: presensi_user
      MYSQL_PASSWORD: secure_password_123
      MYSQL_ROOT_PASSWORD: root_password_123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - presensi-network

  nginx-proxy:
    image: nginx:alpine
    container_name: presensi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - presensi-network

volumes:
  mysql_data:

networks:
  presensi-network:
    driver: bridge 