services:
  app:
    build: .
    container_name: presensi-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SESSION_DRIVER=database
      - CACHE_STORE=database
      - QUEUE_CONNECTION=database
    networks:
      - presensi-network

  nginx:
    image: nginx:alpine
    container_name: presensi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.production.conf:/etc/nginx/nginx.conf
      - storage_data:/var/www/html/storage:ro
    depends_on:
      - app
    networks:
      - presensi-network

volumes:
  storage_data:
  cache_data:

networks:
  presensi-network:
    driver: bridge 