name: Deploy Laravel to Azure

on:
  push:
    branches:
      - master  # Ganti jika branch kamu berbeda

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo, pdo_mysql
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Copy .env (optional)
      run: cp .env.example .env

    - name: Generate APP_KEY
      run: php artisan key:generate

    - name: Cache Laravel config
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Make startup.sh executable
      run: chmod +x startup.sh

    name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D8173D1CCDED4776871213EF191D7C85 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8F12746D83FB4E559CD56E22355F7463 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_99CF1AFCA6414930947DA909F7A6B6BE }}

    - name: Upload to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'presensi-karyawan'         # Ganti sesuai App Service kamu
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
